name: _tmp-lockfile

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo generate-lockfile
      - uses: actions/upload-artifact@v4
        with:
          name: Cargo.lock
          path: Cargo.lock
